export enum ResponseCode
{
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
    SUCCESS = "SUCCESS",
    INVALID_TOKEN = "INVALID_TOKEN",
    SERVER_ERROR = "SERVER_ERROR",
    ERROR = "ERROR",
    PENDING = "PENDING"
}