// Derived lifecycle event types. These are reconstructed from domain state +
// timestamps + assignment history + ledgers; they are NOT read from an audit log.
export enum LifecycleEventType {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',

  DEPOSIT_INITIATED = 'DEPOSIT_INITIATED',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  DEPOSIT_FAILED = 'DEPOSIT_FAILED',
  DEPOSIT_REFUNDED = 'DEPOSIT_REFUNDED',
  DEPOSIT_FORFEITED = 'DEPOSIT_FORFEITED',

  ASSIGNMENT_TASK_CREATED = 'ASSIGNMENT_TASK_CREATED',
  ASSIGNMENT_TASK_TRANSITION = 'ASSIGNMENT_TASK_TRANSITION',

  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',

  VISIT_CREATED = 'VISIT_CREATED',
  VISIT_CHECKED_IN = 'VISIT_CHECKED_IN',
  VISIT_STARTED = 'VISIT_STARTED',
  VISIT_COMPLETED = 'VISIT_COMPLETED',
  VISIT_CANCELLED = 'VISIT_CANCELLED',
  VISIT_NO_SHOW = 'VISIT_NO_SHOW',

  ENCOUNTER_CREATED = 'ENCOUNTER_CREATED',

  BILLING_CREATED = 'BILLING_CREATED',
  BILLING_FINALIZED = 'BILLING_FINALIZED',
  BILLING_PAID = 'BILLING_PAID',

  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',

  SLOT_RESERVED = 'SLOT_RESERVED',
  SLOT_COMPLETED = 'SLOT_COMPLETED',
  SLOT_RELEASED = 'SLOT_RELEASED',

  COIN_EARNED = 'COIN_EARNED',
  COIN_SPENT = 'COIN_SPENT',

  NOTIFICATION_SENT = 'NOTIFICATION_SENT',

  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',

  // Catch-all for a record that references the appointment but cannot be placed.
  UNLINKED_EVENT = 'UNLINKED_EVENT',
}
