export enum WarningSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
}

export enum WarningScope {
  NODE = 'NODE',
  EDGE = 'EDGE',
  TREE = 'TREE',
}

// Machine-readable warning codes the FE can switch on.
export enum WarningCode {
  AUDIT_MISSING = 'AUDIT_MISSING',
  PAYMENT_RECORD_EXPIRED = 'PAYMENT_RECORD_EXPIRED',
  REF_UNRESOLVED = 'REF_UNRESOLVED',
  LEGACY_STATUS = 'LEGACY_STATUS',
  LEGACY_RECORD = 'LEGACY_RECORD',
  SLOT_HISTORY_UNAVAILABLE = 'SLOT_HISTORY_UNAVAILABLE',
  ACTOR_UNKNOWN = 'ACTOR_UNKNOWN',
  NO_CHECKIN_TIMESTAMP = 'NO_CHECKIN_TIMESTAMP',
  MISSING_VISIT = 'MISSING_VISIT',
  MISSING_BILLING = 'MISSING_BILLING',
  WEAK_BILLING_LINK = 'WEAK_BILLING_LINK',
  BRANCH_RECONSTRUCTION_FAILED = 'BRANCH_RECONSTRUCTION_FAILED',
  CONFLICT_MULTIPLE_ACTIVE_TASKS = 'CONFLICT_MULTIPLE_ACTIVE_TASKS',
  CONFLICT_COMPLETED_WITHOUT_VISIT = 'CONFLICT_COMPLETED_WITHOUT_VISIT',
  CONFLICT_BILLING_PAID_APPOINTMENT_NOT_COMPLETED = 'CONFLICT_BILLING_PAID_APPOINTMENT_NOT_COMPLETED',
  CONFLICT_DEPOSIT_PAID_WITHOUT_PAYMENT = 'CONFLICT_DEPOSIT_PAID_WITHOUT_PAYMENT',
  MISSING_TIMESTAMP = 'MISSING_TIMESTAMP',
  RESCHEDULE_HISTORY_UNAVAILABLE = 'RESCHEDULE_HISTORY_UNAVAILABLE',
  NODE_DETAIL_INCOMPLETE = 'NODE_DETAIL_INCOMPLETE',
}
